### ISSUE TITLE
Boolean type conversion issue

### ISSUE THREAD

**Issue by mehmetboraezer** [nicolasblanco/rails_param#48]
## Basic Info

* rails_param Version: `0.10.2`
* Ruby Version: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`
* Rails Version: `5.2.1`

## Issue description
Type conversion not working correctly for the boolean type. I think it should return a bad request if conversion is not possible.

## Steps to reproduce
- Create sample parameter
  ```ruby
  param!(:example, Integer, required: true, blank: false)
  ```
- Send following JSON as request body
  ```json
  {
      "example": true
  } 
  ```
- It should raise an error
  ```shell
  can't convert true into Integer

  /Users/bora/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rails_param-0.10.2/lib/rails_param/param.rb:106:in `Integer'
  /Users/bora/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rails_param-0.10.2/lib/rails_param/param.rb:106:in `coerce'
  /Users/bora/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rails_param-0.10.2/lib/rails_param/param.rb:28:in `param!'
  ```

**Comment by iMacTia** [comment]
@mehmetboraezer apologies for the slow reply 😅.
You're completely right, we should be raising an `InvalidParameterError` in this case like all other type coercions, not sure why it's different for this one.
Will investigate further.

**Comment by iMacTia** [comment]
@mehmetboraezer after a quick investigation I may have found the problem:

> Type initializers (e.g. `Integer()`) raise a `TypeError` when passed some types (e.g. Boolean), and `ArgumentError` for others (e.g. String).

#54 should take care of it 👍

**Comment by mehmetboraezer** [comment]
@iMacTia I checked your PR. It seems cool for the issue. I will close this issue when PR merge. Thanks for help. 👍
